### ISSUE TITLE
`posthog-node` v4.10.2+ breaks our TypeScript build

### ISSUE THREAD

**Issue by simon-abbott** [PostHog/posthog-js-lite#448]
## Bug description

Trying to build with `posthog-node` v4.10.2 or greater causes the error:

```
node_modules/posthog-node/lib/index.d.ts:32:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

32 enum SurveyPosition {
   ~~~~
```

## How to reproduce

1. Install `posthog-node` v4.10.2 or greater
2. Install the latest version of `typescript` (I tested against v5.8.3)
3. Use `posthog-node` in a `.ts` file somewhere in the project
4. Try to build

## Related sub-libraries

- [ ] All of them
- [ ] posthog-web
- [x] posthog-node
- [ ] posthog-ai
- [ ] posthog-react-native

**Comment by marandaneto** [comment]
@simon-abbott 

thanks for reporting, our CI didn't fail though, strange.
I'll add a quick workaround and cut a version.

**Comment by simon-abbott** [comment]
Yeah, I'm surprised nobody else ran into this issue either, especially since I was able to reproduce it with a clean project. Thanks for the quick triage!

**Comment by simon-abbott** [comment]
@marandaneto Unfortunately that didn't seem to fix the issue. I put together a [StackBlitz repro](https://stackblitz.com/edit/stackblitz-starters-4mx6ztx4?file=index.ts) to hopefully help.

**Comment by marandaneto** [comment]
> [@marandaneto](https://github.com/marandaneto) Unfortunately that didn't seem to fix the issue. I put together a [StackBlitz repro](https://stackblitz.com/edit/stackblitz-starters-4mx6ztx4?file=index.ts) to hopefully help.

i did create an empty app locally and it worked, well... (probably TS versioning?)
let's give another try with https://github.com/PostHog/posthog-js-lite/pull/451

**Comment by lucasheriques** [comment]
@marandaneto i didn't have the time today, but will find some time to check soon if you can't figure out

**Comment by marandaneto** [comment]
@simon-abbott https://github.com/PostHog/posthog-js-lite/releases/tag/posthog-node-v4.11.6 i think this one should have worked, let us know if not, sorry about that.

**Comment by simon-abbott** [comment]
That one seems to have worked! Thank you!
